services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/webserver/domain.cert.pem:/etc/nginx/ssl/domain.cert.pem
      - /etc/ssl/webserver/private.key.pem:/etc/nginx/ssl/private.key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always